# Generated by Django 5.1 on 2024-10-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_business_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='facebook_pid',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='google_pid',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='yelp_url',
            field=models.TextField(null=True),
        ),
    ]
