# Generated by Django 5.1 on 2024-10-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_business_facebook_pid_business_google_pid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='rating',
            new_name='facebook_rating',
        ),
        migrations.AddField(
            model_name='business',
            name='google_rating',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='yelp_rating',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
