# Generated by Django 5.1 on 2024-10-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_rating_business_facebook_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='reviews_count',
            new_name='facebook_reviews_count',
        ),
        migrations.AddField(
            model_name='business',
            name='google_reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='yelp_reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
