# Generated by Django 5.1 on 2024-10-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_reviews_count_business_facebook_reviews_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
