# Generated by Django 5.1 on 2024-10-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
