# Generated by Django 5.1 on 2024-10-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_business_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='hours',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='thumbnail',
            field=models.TextField(null=True),
        ),
    ]
