# Generated by Django 5.1 on 2024-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_business_last_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_cid',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='google_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
