# Generated by Django 5.1 on 2024-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_business_google_cid_business_google_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
