# Generated by Django 5.1 on 2024-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_business_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
