# Generated by Django 5.1 on 2024-10-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_business_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstypes',
            name='created_by',
        ),
    ]
