# Generated by Django 4.0.10 on 2024-10-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_businesscategory_businesscategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessreviews',
            name='content',
            field=models.JSONField(),
        ),
    ]
