# Generated by Django 4.0.10 on 2024-10-30 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_businessreviews_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='reviews',
        ),
        migrations.AddField(
            model_name='businessreviews',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.business'),
        ),
    ]
