# Generated by Django 4.0.10 on 2024-10-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_business_facebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='facebook_reviews_count',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='google_reviews_count',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='yelp_reviews_count',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
