# Generated by Django 4.0.10 on 2024-10-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_business_google_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='facebook_rating',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='google_rating',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='yelp_rating',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
    ]
