# Generated by Django 5.1 on 2024-10-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_business_facebook_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
