# Generated by Django 5.1 on 2024-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_business_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='our_rating',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='our_review',
            field=models.TextField(null=True),
        ),
    ]
