# Generated by Django 4.0.10 on 2024-11-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_business_our_rating_business_our_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='featured',
            field=models.BooleanField(default=0),
        ),
    ]
