locations = [
    "Abilene, Texas, United States",
    "Akron, Ohio, United States",
    "Albany, Georgia, United States",
    "Albany, New York, United States",
    "Albuquerque, New Mexico, United States",
    "Altoona, Pennsylvania, United States",
    "Amarillo, Texas, United States",
    "Ames, Iowa, United States",
    "Anchorage, Alaska, United States",
    "Annapolis, Maryland, United States",
    "Ann Arbor, Michigan, United States",
    "Appleton, Wisconsin, United States",
    "Asheville, North Carolina, United States",
    "Ashtabula, Ohio, United States",
    "Athens, Georgia, United States",
    "Athens, Ohio, United States",
    "Atlanta, Georgia, United States",
    "Auburn, Alabama, United States",
    "Augusta, Georgia, United States",
    "Austin, Texas, United States",
    "Bakersfield, California, United States",
    "Baltimore, Maryland, United States",
    "Baton Rouge, Louisiana, United States",
    "Battle Creek, Michigan, United States",
    "Beaumont, Texas, United States",
    "Bellingham, Washington, United States",
    "Bemidji, Minnesota, United States",
    "Bend, Oregon, United States",
    "Billings, Montana, United States",
    "Binghamton, New York, United States",
    "Birmingham, Alabama, United States",
    "Bismarck, North Dakota, United States",
    "Bloomington, Indiana, United States",
    "Bloomington, Illinois, United States",
    "Boise, Idaho, United States",
    "Boone, North Carolina, United States",
    "Boston, Massachusetts, United States",
    "Boulder, Colorado, United States",
    "Bowling Green, Kentucky, United States",
    "Bozeman, Montana, United States",
    "Brainerd, Minnesota, United States",
    "Brownsville, Texas, United States",
    "Brunswick, Georgia, United States",
    "Buffalo, New York, United States",
    "Butte, Montana, United States",
    "Cape Cod, Massachusetts, United States",
    "Catskills, New York, United States",
    "Cedar Rapids, Iowa, United States",
    "Central Louisiana, Louisiana, United States",
    "Central Michigan, Michigan, United States",
    "Central New Jersey, New Jersey, United States",
    "Champaign, Illinois, United States",
    "Charleston, South Carolina, United States",
    "Charleston, West Virginia, United States",
    "Charlotte, North Carolina, United States",
    "Charlottesville, Virginia, United States",
    "Chattanooga, Tennessee, United States",
    "Chautauqua, New York, United States",
    "Chicago, Illinois, United States",
    "Chico, California, United States",
    "Chillicothe, Ohio, United States",
    "Cincinnati, Ohio, United States",
    "Clarksville, Tennessee, United States",
    "Cleveland, Ohio, United States",
    "Clovis, New Mexico, United States",
    "College Station, Texas, United States",
    "Colorado Springs, Colorado, United States",
    "Columbia, South Carolina, United States",
    "Columbus, Georgia, United States",
    "Columbus, Ohio, United States",
    "Cookeville, Tennessee, United States",
    "Corpus Christi, Texas, United States",
    "Corvallis, Oregon, United States",
    "Cumberland Valley, Pennsylvania, United States",
    "Dallas, Texas, United States",
    "Danville, Virginia, United States",
    "Daytona Beach, Florida, United States",
    "Dayton, Ohio, United States",
    "Decatur, Illinois, United States",
    "Deep East Texas, Texas, United States",
    "Delaware, Delaware, United States",
    "Del Rio, Texas, United States",
    "Denver, Colorado, United States",
    "Des Moines, Iowa, United States",
    "Detroit, Michigan, United States",
    "Dothan, Alabama, United States",
    "Dubuque, Iowa, United States",
    "Duluth, Minnesota, United States",
    "Eastern Colorado, Colorado, United States",
    "Eastern Connecticut, Connecticut, United States",
    "Eastern Kentucky, Kentucky, United States",
    "Eastern Montana, Montana, United States",
    "Eastern North Carolina, North Carolina, United States",
    "Eastern Panhandle, West Virginia, United States",
    "Eastern Shore, Maryland, United States",
    "East Idaho, Idaho, United States",
    "East Oregon, Oregon, United States",
    "Eau Claire, Wisconsin, United States",
    "Elko, Nevada, United States",
    "Elmira, New York, United States",
    "El Paso, Texas, United States",
    "Erie, Pennsylvania, United States",
    "Eugene, Oregon, United States",
    "Evansville, Indiana, United States",
    "Fairbanks, Alaska, United States",
    "Fargo, North Dakota, United States",
    "Farmington, New Mexico, United States",
    "Fayetteville, Arkansas, United States",
    "Fayetteville, North Carolina, United States",
    "Finger Lakes, New York, United States",
    "Flagstaff, Arizona, United States",
    "Flint, Michigan, United States",
    "Florence, Alabama, United States",
    "Florence, South Carolina, United States",
    "Florida Keys, Florida, United States",
    "Fort Collins, Colorado, United States",
    "Fort Dodge, Iowa, United States",
    "Fort Smith, Arkansas, United States",
    "Fort Wayne, Indiana, United States",
    "Frederick, Maryland, United States",
    "Fredericksburg, Virginia, United States",
    "Fresno, California, United States",
    "Ft. Myers, Florida, United States",
    "Gadsden, Alabama, United States",
    "Gainesville, Florida, United States",
    "Galveston, Texas, United States",
    "Glens Falls, New York, United States",
    "Gold Country, California, United States",
    "Grand Forks, North Dakota, United States",
    "Grand Island, Nebraska, United States",
    "Grand Rapids, Michigan, United States",
    "Great Falls, Montana, United States",
    "Green Bay, Wisconsin, United States",
    "Greensboro, North Carolina, United States",
    "Greenville, South Carolina, United States",
    "Gulfport, Mississippi, United States",
    "Hanford, California, United States",
    "Harrisburg, Pennsylvania, United States",
    "Harrisonburg, Virginia, United States",
    "Hartford, Connecticut, United States",
    "Hattiesburg, Mississippi, United States",
    "Hawaii, Hawaii, United States",
    "Heartland Florida, Florida, United States",
    "Helena, Montana, United States",
    "Hickory, North Carolina, United States",
    "High Rockies, Colorado, United States",
    "Hilton Head, South Carolina, United States",
    "Holland, Michigan, United States",
    "Houma, Louisiana, United States",
    "Houston, Texas, United States",
    "Hudson Valley, New York, United States",
    "Humboldt County, California, United States",
    "Huntington, West Virginia, United States",
    "Huntsville, Alabama, United States",
    "Imperial County, California, United States",
    "Indianapolis, Indiana, United States",
    "Inland Empire, California, United States",
    "Iowa City, Iowa, United States",
    "Ithaca, New York, United States",
    "Jackson, Michigan, United States",
    "Jackson, Mississippi, United States",
    "Jackson, Tennessee, United States",
    "Jacksonville, Florida, United States",
    "Jacksonville, North Carolina, United States",
    "Janesville, Wisconsin, United States",
    "Jersey Shore, New Jersey, United States",
    "Jonesboro, Arkansas, United States",
    "Joplin, Missouri, United States",
    "Kalamazoo, Michigan, United States",
    "Kalispell, Montana, United States",
    "Kansas City, Missouri, United States",
    "Kenai Peninsula, Alaska, United States",
    "Kennewick, Washington, United States",
    "Kenosha, Wisconsin, United States",
    "Killeen, Texas, United States",
    "Kirksville, Missouri, United States",
    "Klamath Falls, Oregon, United States",
    "Knoxville, Tennessee, United States",
    "Kokomo, Indiana, United States",
    "La Crosse, Wisconsin, United States",
    "Lafayette, Louisiana, United States",
    "Lake Charles, Louisiana, United States",
    "Lakeland, Florida, United States",
    "Lake of the Ozarks, Missouri, United States",
    "Lancaster, Pennsylvania, United States",
    "Lansing, Michigan, United States",
    "Laredo, Texas, United States",
    "La Salle County, Illinois, United States",
    "Las Cruces, New Mexico, United States",
    "Las Vegas, Nevada, United States",
    "Lawrence, Kansas, United States",
    "Little Rock, Arkansas, United States",
    "Longview, Texas, United States",
    "Long Island, New York, United States",
    "Los Angeles, California, United States",
    "Louisville, Kentucky, United States",
    "Lubbock, Texas, United States",
    "Lynchburg, Virginia, United States",
    "Macon, Georgia, United States",
    "Madison, Wisconsin, United States",
    "Manchester, New Hampshire, United States",
    "Manhattan, Kansas, United States",
    "Mansfield, Ohio, United States",
    "Marquette, Michigan, United States",
    "Medford, Oregon, United States",
    "Memphis, Tennessee, United States",
    "Miami, Florida, United States",
    "Michigan City, Indiana, United States",
    "Midland, Texas, United States",
    "Milwaukee, Wisconsin, United States",
    "Minneapolis, Minnesota, United States",
    "Missoula, Montana, United States",
    "Mobile, Alabama, United States",
    "Modesto, California, United States",
    "Montgomery, Alabama, United States",
    "Morgantown, West Virginia, United States",
    "Myrtle Beach, South Carolina, United States",
    "Naples, Florida, United States",
    "Nashville, Tennessee, United States",
    "New Bedford, Massachusetts, United States",
    "New Bern, North Carolina, United States",
    "New Britain, Connecticut, United States",
    "New Orleans, Louisiana, United States",
    "New York City, New York, United States",
    "Newark, New Jersey, United States",
    "Norfolk, Virginia, United States",
    "North Carolina, North Carolina, United States",
    "North Dakota, North Dakota, United States",
    "Northern Michigan, Michigan, United States",
    "Northern New Jersey, New Jersey, United States",
    "Northwest Arkansas, Arkansas, United States",
    "Ocala, Florida, United States",
    "Ocean City, New Jersey, United States",
    "Oklahoma City, Oklahoma, United States",
    "Omaha, Nebraska, United States",
    "Orlando, Florida, United States",
    "Oshkosh, Wisconsin, United States",
    "Ottawa, Illinois, United States",
    "Palm Beach, Florida, United States",
    "Palm Springs, California, United States",
    "Panama City, Florida, United States",
    "Parkersburg, West Virginia, United States",
    "Pasco, Washington, United States",
    "Peoria, Illinois, United States",
    "Philadelphia, Pennsylvania, United States",
    "Phoenix, Arizona, United States",
    "Pittsburgh, Pennsylvania, United States",
    "Pocatello, Idaho, United States",
    "Portland, Oregon, United States",
    "Portsmouth, New Hampshire, United States",
    "Poughkeepsie, New York, United States",
    "Providence, Rhode Island, United States",
    "Provo, Utah, United States",
    "Raleigh, North Carolina, United States",
    "Reno, Nevada, United States",
    "Richmond, Virginia, United States",
    "Riverside, California, United States",
    "Roanoke, Virginia, United States",
    "Rochester, Minnesota, United States",
    "Rochester, New York, United States",
    "Rockford, Illinois, United States",
    "Sacramento, California, United States",
    "St. Louis, Missouri, United States",
    "St. Petersburg, Florida, United States",
    "Salem, Oregon, United States",
    "Salt Lake City, Utah, United States",
    "San Angelo, Texas, United States",
    "San Antonio, Texas, United States",
    "San Diego, California, United States",
    "San Francisco, California, United States",
    "San Jose, California, United States",
    "Santa Barbara, California, United States",
    "Santa Fe, New Mexico, United States",
    "Savannah, Georgia, United States",
    "Scranton, Pennsylvania, United States",
    "Seattle, Washington, United States",
    "Sierra Vista, Arizona, United States",
    "Sioux City, Iowa, United States",
    "Sioux Falls, South Dakota, United States",
    "South Bend, Indiana, United States",
    "South Carolina, South Carolina, United States",
    "South Dakota, South Dakota, United States",
    "South Texas, Texas, United States",
    "Spokane, Washington, United States",
    "Springfield, Illinois, United States",
    "Springfield, Massachusetts, United States",
    "St. Cloud, Minnesota, United States",
    "Syracuse, New York, United States",
    "Tallahassee, Florida, United States",
    "Tampa, Florida, United States",
    "Terre Haute, Indiana, United States",
    "Toledo, Ohio, United States",
    "Topeka, Kansas, United States",
    "Traverse City, Michigan, United States",
    "Tulsa, Oklahoma, United States",
    "Tuscaloosa, Alabama, United States",
    "Twin Cities, Minnesota, United States",
    "Tyler, Texas, United States",
    "Utica, New York, United States",
    "Vancouver, Washington, United States",
    "Victoria, Texas, United States",
    "Virginia Beach, Virginia, United States",
    "Waco, Texas, United States",
    "Wichita, Kansas, United States",
    "Wilmington, North Carolina, United States",
    "Wilson, North Carolina, United States",
    "Winchester, Virginia, United States",
    "Winona, Minnesota, United States",
    "Wisconsin Rapids, Wisconsin, United States",
    "Worcester, Massachusetts, United States",
    "Yakima, Washington, United States",
    "York, Pennsylvania, United States",
    "Youngstown, Ohio, United States",
    "Yuba City, California, United States",
]
